// <-- This file is generated by xedithor. Don't edit this --> 

package test.game.xdr;

interface DATA_SPRITE
{
	public final static int SPR_LUCK = 1;
	public final static int SPR_PRINCE = 2;
	public final static int SPR_WALKANIM = 3;
	public final static int COUNT = 4;
}
