// <-- This file is generated by xedithor. Don't edit this --> 

package test.game.xdr;

interface SPRITE_SOLDIER
{
	public final static int FRAME__0 = 0;
	public final static int FRAME__1 = 1;
	public final static int FRAME__2 = 2;
	public final static int FRAME__3 = 3;
	public final static int FRAME__4 = 4;
	public final static int FRAME__5 = 5;
	public final static int FRAME__6 = 6;
	public final static int FRAME__7 = 7;
	public final static int FRAME__8 = 8;
	public final static int FRAME__9 = 9;
	public final static int FRAME__10 = 10;
	public final static int FRAME__11 = 11;
	public final static int FRAME__12 = 12;
	public final static int FRAME__13 = 13;
	public final static int FRAME__14 = 14;
	public final static int FRAME__15 = 15;
	public final static int FRAME__16 = 16;
	public final static int FRAME__17 = 17;
	public final static int FRAME__18 = 18;
	public final static int FRAME__19 = 19;
	public final static int FRAME__20 = 20;
	public final static int FRAME__21 = 21;
	public final static int FRAME_22 = 22;
	public final static int FRAME_23 = 23;
	public final static int FRAME_24 = 24;
	public final static int FRAME_25 = 25;
	public final static int FRAME_26 = 26;
	public final static int FRAME_27 = 27;
	public final static int FRAME_28 = 28;
	public final static int FRAME_29 = 29;
	public final static int FRAME_30 = 30;
	public final static int FRAME_31 = 31;
	public final static int FRAME_32 = 32;
	public final static int FRAME_33 = 33;
	public final static int FRAME_34 = 34;
	public final static int FRAME_35 = 35;
	public final static int FRAME_36 = 36;
	public final static int FRAME_37 = 37;
	public final static int FRAME_COUNT = 38;

	public final static int BOMBER_0 = 0;
	public final static int TROWGRANAT_1 = 1;
	public final static int ANIM_COUNT = 2;
}
