// <-- This file is generated by xedithor. Don't edit this --> 

package test.game.xdr;

interface SPRITE_WALKANIM
{
	public final static int FRAME_0 = 0;
	public final static int FRAME_1 = 1;
	public final static int FRAME_2 = 2;
	public final static int FRAME_3 = 3;
	public final static int FRAME_4 = 4;
	public final static int FRAME_5 = 5;
	public final static int FRAME_6 = 6;
	public final static int FRAME_7 = 7;
	public final static int FRAME_COUNT = 8;

	public final static int ANIM_0 = 0;
	public final static int ANIM_COUNT = 1;
}
